/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tristan_sun_nativeegl_demo_NativeEglExample */

#ifndef _Included_com_tristan_sun_nativeegl_demo_NativeEglExample
#define _Included_com_tristan_sun_nativeegl_demo_NativeEglExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tristan_sun_nativeegl_demo_NativeEglExample
 * Method:    drawBackgroud
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_tristan_sun_nativeegl_demo_NativeEglExample_drawBackgroud
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
